# action.yml
name: AI Code Reviewer
description: Reviews PRs using OpenAI
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
      python-version: "3.10"

    - run: pip install requests
      shell: bash

    - run: python code_review.py
    shell: bash
